spring.application.name=carepoint
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.initialization-mode=always
spring.datasource.platform=postgresql
spring.datasource.continue-on-error=true
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.profiles.active=dev
logging.level.liquibase=WARN
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=100MB

